# Generated by Django 5.1.2 on 2024-10-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
