# Generated by Django 5.1.2 on 2024-10-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('payed', 'Payed'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
